name: Build Brick Breaker Client

on:
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        arch: [x64, arm64]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.6.2"
          cabal-version: "3.10.1.0"
      - name: Compile
        run: cabal build brick-breaker-client
